version: '3.8'
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0 --port 8545 --offline
    ports:
      - "8545:8545"
  bundler:
    build: ./services/bundler
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - anvil
  web:
    build: ./apps/web
    environment:
      - PORT=4000
      - NEXT_PUBLIC_BUNDLER_URL=http://bundler:3000
    ports:
      - "4000:4000"
    depends_on:
      - bundler
